"""Versioned registry of commercial claims and their prerequisites (C05-A08).

Four claim kinds with DIFFERENT prerequisites, which must never be conflated:

  calculation_verified   -- "cálculo verificado": the SOFTWARE/version passed an
                            independent numeric reference. Says nothing about
                            any specific avaliação or about normative scope.
  implements_requirements -- "implementa os requisitos X/Y da edição Z": the
                            rules are implemented AND their thresholds were
                            read against that edition. Bound to an edition.
  profile_compatible     -- "compatível com o perfil documental P": the
                            product emits what profile P documents, where P was
                            obtained from a legitimate source. NOT acceptance.
  institution_accepted   -- "aceito/homologado pela instituição I": requires a
                            real act by I, with version and scope. A
                            credenciamento, a supplier registry or a licitação
                            is NOT this act.

Rules the registry enforces:
  - a claim whose evidence is missing is BLOCKED, never downgraded silently;
  - evidence of one accepted laudo does not validate other profiles/versions;
  - a professional's certification does not certify the software;
  - a permissive library licence is not a certification of anything.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Mapping, Optional

CLAIMS_REGISTRY_VERSION = "c05.claims/1"

CLAIM_CALCULATION_VERIFIED = "calculation_verified"
CLAIM_IMPLEMENTS_REQUIREMENTS = "implements_requirements"
CLAIM_PROFILE_COMPATIBLE = "profile_compatible"
CLAIM_INSTITUTION_ACCEPTED = "institution_accepted"

CLAIM_KINDS = (
    CLAIM_CALCULATION_VERIFIED,
    CLAIM_IMPLEMENTS_REQUIREMENTS,
    CLAIM_PROFILE_COMPATIBLE,
    CLAIM_INSTITUTION_ACCEPTED,
)

#: Scope of what each claim kind is about. A claim may only be asserted about
#: its own scope: a case-level fact never licenses a product-level claim.
CLAIM_SCOPE = {
    CLAIM_CALCULATION_VERIFIED: "software_version",
    CLAIM_IMPLEMENTS_REQUIREMENTS: "software_version_and_edition",
    CLAIM_PROFILE_COMPATIBLE: "software_version_and_profile",
    CLAIM_INSTITUTION_ACCEPTED: "institution_and_profile_and_version",
}

CLAIM_PREREQUISITES: Dict[str, Dict[str, Any]] = {
    CLAIM_CALCULATION_VERIFIED: {
        "requires": [
            "independent_numeric_reference_passed",
            "software_version_identified",
        ],
        "forbidden_substitutes": [
            "passing the product's own tests only",
            "an oracle generated by the very code under test",
        ],
        "wording_template": (
            "Cálculo verificado contra referência numérica independente "
            "({reference}) na versão {version}."
        ),
    },
    CLAIM_IMPLEMENTS_REQUIREMENTS: {
        "requires": [
            "rules_implemented_and_tested",
            "thresholds_read_against_edition",
            "edition_identified",
        ],
        "forbidden_substitutes": [
            "clause labels copied from a README or a secondary source",
            "model memory of the threshold",
        ],
        "wording_template": (
            "Implementa os requisitos {requirements} da edição {edition}, com "
            "limiares conferidos contra o texto dessa edição."
        ),
    },
    CLAIM_PROFILE_COMPATIBLE: {
        "requires": [
            "profile_obtained_from_legitimate_source",
            "profile_state_verified",
            "product_emits_profile_requirements",
        ],
        "forbidden_substitutes": [
            "inferring the profile from a supplier registry",
            "inferring the profile from one accepted laudo",
        ],
        "wording_template": (
            "Compatível com o perfil documental {profile} versão {profile_version}. "
            "Compatibilidade documental não é aceitação pela instituição."
        ),
    },
    CLAIM_INSTITUTION_ACCEPTED: {
        "requires": [
            "real_act_by_institution",
            "act_type_is_homologacao_or_explicit_acceptance",
            "act_version_and_scope_recorded",
        ],
        "forbidden_substitutes": [
            "credenciamento profissional",
            "contratação de empresa",
            "supplier registry / cadastro de fornecedor",
            "licitação participation",
            "a professional's own certification",
            "a digital signature or an authorship record",
            "a permissive licence of a third-party library",
        ],
        "wording_template": (
            "Aceito pela instituição {institution} conforme {act} "
            "(versão {act_version}, escopo {act_scope})."
        ),
    },
}

CLAIM_PERMITTED = "permitted"
CLAIM_BLOCKED = "blocked"


class ClaimNotPermitted(RuntimeError):
    """Raised when a claim is asserted without its prerequisites."""


def evaluate_claim(
    kind: str,
    *,
    evidence: Optional[Mapping[str, Any]] = None,
    subject: Optional[Mapping[str, Any]] = None,
) -> Dict[str, Any]:
    """Decide whether a claim is permitted, and with exactly what wording.

    ``evidence`` maps prerequisite ids to a truthy evidence reference. A
    prerequisite backed by something in ``forbidden_substitutes`` is rejected
    even when present.
    """
    if kind not in CLAIM_KINDS:
        raise ValueError(f"tipo de alegação desconhecido: {kind!r}")
    spec = CLAIM_PREREQUISITES[kind]
    ev = dict(evidence or {})
    subj = dict(subject or {})

    missing: List[str] = [r for r in spec["requires"] if not ev.get(r)]
    rejected: List[Dict[str, str]] = []
    for req in spec["requires"]:
        val = ev.get(req)
        if not isinstance(val, Mapping):
            continue
        basis = str(val.get("basis") or "")
        for bad in spec["forbidden_substitutes"]:
            if basis and bad.lower() in basis.lower():
                rejected.append({"requirement": req, "basis": basis, "forbidden": bad})

    if missing or rejected:
        reasons = []
        if missing:
            reasons.append(f"pré-requisitos ausentes: {missing}")
        if rejected:
            reasons.append(f"substitutos vedados: {rejected}")
        return {
            "kind": kind,
            "scope": CLAIM_SCOPE[kind],
            "state": CLAIM_BLOCKED,
            "registry_version": CLAIMS_REGISTRY_VERSION,
            "missing": missing,
            "rejected": rejected,
            "permitted_wording": None,
            "detail": (
                f"Alegação {kind!r} BLOQUEADA: " + "; ".join(reasons) + ". "
                "Ausência de prova não é permissão implícita."
            ),
        }

    try:
        wording = spec["wording_template"].format(**subj)
    except KeyError as exc:
        return {
            "kind": kind,
            "scope": CLAIM_SCOPE[kind],
            "state": CLAIM_BLOCKED,
            "registry_version": CLAIMS_REGISTRY_VERSION,
            "missing": [f"subject.{exc.args[0]}"],
            "rejected": [],
            "permitted_wording": None,
            "detail": (
                f"Alegação {kind!r} BLOQUEADA: o sujeito da alegação não identifica "
                f"{exc.args[0]!r}; uma alegação sem versão/escopo não é verificável."
            ),
        }

    return {
        "kind": kind,
        "scope": CLAIM_SCOPE[kind],
        "state": CLAIM_PERMITTED,
        "registry_version": CLAIMS_REGISTRY_VERSION,
        "missing": [],
        "rejected": [],
        "permitted_wording": wording,
        "evidence_refs": [ev[r] for r in spec["requires"]],
        "detail": f"Alegação {kind!r} permitida no escopo {CLAIM_SCOPE[kind]!r}.",
    }


def assert_claim(kind: str, **kwargs: Any) -> Dict[str, Any]:
    """evaluate_claim, but raises instead of returning a blocked claim."""
    result = evaluate_claim(kind, **kwargs)
    if result["state"] != CLAIM_PERMITTED:
        raise ClaimNotPermitted(result["detail"])
    return result


def reuse_acceptance_check(
    claim: Mapping[str, Any],
    *,
    target_profile: Optional[str] = None,
    target_version: Optional[str] = None,
) -> Dict[str, Any]:
    """Refuse re-use of an institutional acceptance outside its exact scope.

    An acceptance recorded for profile P at version V says nothing about
    another profile or another version.
    """
    if claim.get("kind") != CLAIM_INSTITUTION_ACCEPTED:
        return {"reusable": False, "detail": "apenas aceitação institucional tem escopo reaproveitável."}
    scope = claim.get("granted_scope") or {}
    same_profile = target_profile is None or scope.get("profile") == target_profile
    same_version = target_version is None or scope.get("version") == target_version
    if same_profile and same_version:
        return {
            "reusable": True,
            "detail": (
                f"Aceitação válida para perfil {scope.get('profile')!r} "
                f"versão {scope.get('version')!r}."
            ),
        }
    return {
        "reusable": False,
        "detail": (
            f"Aceitação concedida para perfil {scope.get('profile')!r} versão "
            f"{scope.get('version')!r} NÃO se estende a perfil {target_profile!r} "
            f"versão {target_version!r}. Reaproveitamento indevido de aceite."
        ),
    }
